export const FETCHING_CATEGORIES = 'FETCHING_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const REGISTER_ATTEMPT = 'REGISTER_ATTEMPT';
export const REGISTER_SUCCESFULLY = 'REGISTER_SUCCESFULLY';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESFULLY = 'LOGIN_SUCCESFULLY';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_ATTEMPT = 'LOGOUT_ATTEMPT';
export const LOGOUT_SUCCESFULLY = 'LOGOUT_SUCCESFULLY';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const UPDATE_PROFILE_ATTEMPT = 'UPDATE_PROFILE_ATTEMPT'; 
export const UPDATE_PROFILE_SUCCESFULLY = 'UPDATE_PROFILE_SUCCESFULLY'; 
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'; 

export const LOGIN_PASS = 'LOGIN_PASS';

export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';

export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
export const FETCHING_PRODUCT = 'FETCHING_PRODUCT';

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
export const FETCHING_ORDERS = 'FETCHING_ORDERS';

export const FETCH_ADS_FAILURE = 'FETCH_ADS_FAILURE';
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';
export const FETCHING_ADS = 'FETCHING_ADS';

export const ADDING_ATTEMPT = 'ADDING_ATTEMPT';
export const ADDED_SUCCESFULLY = 'ADDED_SUCCESFULLY';
export const ADDING_FAILED = 'ADDING_FAILED';

export const EDITING_ATTEMPT = 'EDITING_ATTEMPT';
export const EDITTED_SUCCESFULLY = 'EDITTED_SUCCESFULLY';
export const EDITING_FAILED = 'EDITING_FAILED';

export const DELETING_ATTEMPT = 'DELETING_ATTEMPT';
export const DELETED_SUCCESFULLY = 'DELETED_SUCCESFULLY';
export const DELETING_FAILED = 'DELETING_FAILED';