import LocalizedStrings from "react-native-localization";
export default localization = new LocalizedStrings({
    en: {
        home: 'Home',
        menu: 'Menu',
        search: 'Search',
        cart: 'cart',
        settings: 'Settings',
        add:'add',
        SearchPlaceHolder:'what are you searching for',
        merchentName:'Baalat Elzad',
        freeDlievery:'free delivery',
        homeDrawer:'Home',
        profileDrawer:'Profile',
        cartDrawer:'My Cart',
        call_usDrawer:'Call us',
        conditionsDrawer:'Conditions',
        exitDrawer:'Exit',
        search:'search',
        cartProductName:'Name',
        cartProductWeight:'Weight',
        cartProductQuantity:'Quantity',
        cartProductPrice:'Price',
        MyOrders:'My Orders',
        signup:'Register',
        RegisterClient:'Register Client',
        registerUsername:'Client name',
        registerPhone:'phone',
        registerPassword:'password',
        registerReEnterPassword:'re-enter password',
        Signin:'Sign in',
        login:'login',
        arabic:'Arabic',
        english:'English',
        restartApp:'please restart the app to set the new configurations.',
        shipping:'Cart Shipping',
        continueShipping:'continue to shipping',
        current:'Current',
        previous:'Previous',
        registerNew:'Signup',
        forgetPassword:'forget password ?',
        registerAddress:'address',
        chooseLanguage:'Choose Language',
        updatePassword:'update password',
        updatePhone:'update phone',
        updatePasswordOld:'old password',
        updatePasswordNew:'new password',
        updatePasswordConfirmNew:'re-enter password',
        

        registerMerchentname:'merchent name',
        registerWorkingHours:'working hours form ... to ...',
        registerMerchentPhoto:'take photo',
        agreeToConds:'agree to conditions',
        RegisterMerchent:'Register Merchent',
        newOrders:'New Orders',
        clientName:'Client Name',
        total:'total',
        accept:'Accept',
        call:'Call',
        finishOrder:'Finish Order',
        cancel:'Cancel',
        phone:'Phone',
    },
    ar: {
        home: 'الرئيسية',
        menu: 'القائمة',
        search: 'البحث',
        cart: 'العربة',
        settings: 'الإعدادات',
        add:'أضف',
        SearchPlaceHolder:'ما الذي تبحث عنه',
        merchentName:'بقالة الزاد',
        freeDlievery:'توصيل مجاني',
        homeDrawer:'الصفحه الرئيسية',
        profileDrawer:'الصفحة الشخصية',
        cartDrawer:'مشترياتي',
        call_usDrawer:'إتصل بنا',
        conditionsDrawer:'الشروط والأحكام',
        exitDrawer:'خروج',
        search:'بحث',
        cartProductName:'الإسم',
        cartProductWeight:'الوزن',
        cartProductQuantity:'الكمية',
        cartProductPrice:'السعر',
        MyOrders:'طلباتي',
        signup:'تسجيل',
        RegisterClient:'تسجيل عميل',
        registerUsername:'اسم العميل',
        registerPhone:'رقم الجوال',
        registerPassword:'كلمة المرور',
        registerReEnterPassword:'إعادة كلمة المرور',
        Signin:'تسجيل الدخول',
        login:'دخول',
        arabic:'عربي',
        english:'إنجليزي',
        restartApp:'من فضلك اعد تحميل التطبيق لتفعيل التغيرات الجديدة.',
        shipping:'سلة الشراء',
        continueShipping:'متابعة عملية الشراء',
        current:'الحالية',
        previous:'السابقة',
        registerNew:'مستخدم جديد',
        forgetPassword:'نسيت كلمة المرور؟',
        registerAddress:'العنوان',
        chooseLanguage:'إختر لغة',
        updatePassword:'تغيير كلمة المرور',
        updatePhone:'تغيير رقم الجوال',
        updatePasswordOld:'كلمة المرور القديمة',
        updatePasswordNew:'كلمة المرور الجديدة',
        updatePasswordConfirmNew:'اعادة كلمة المرور',
        

        registerMerchentname:'إسم البقالة',
        registerWorkingHours:'ساعات العمل من ...الي ...',
        registerMerchentPhoto:'رفع صورة',
        agreeToConds:'الموافقه علي الشروط والاحكام',
        RegisterMerchent:'تسجيل البقالة',
        newOrders:'طلباتي الجديدة',
        clientName:'اسم العميل',
        total:'المجموع',
        accept:'قبول',
        call:'إتصال',
        finishOrder:'إنهاء الطلب',
        cancel:'إلغاء',
        phone:'رقم الجوال',
    }
})
