import LocalizedStrings from "react-native-localization";
export default localization = new LocalizedStrings({
    en: {
        travelDate:'Travel Date',
        arrivalDate:'Arrival Date',
        travelDetails:'Travel Details',
        agree:'Agree',
        goingComingBack:'Going-coming back',
        going:'Going',
        goingFrom:'Source',
        backTo:'Destination',
        numberOfPersons:'Number of persons',
        specialDicount:'Special Discount',
        Promocode:'Promocode',
        myBooks:'My Books',
        currentBooks:'Currnt Books',
        previousBooks:'Previous Books',
        travelType:'Travel Type',
        sourceDestination:'Source and Destination',
        travelNumber:'Travel Number',
        callUs:'Call Us',
        userName:'username',
        phoneNumber:'phone number',
        messege:'Messege',
        send:'Send',
        chat:'Chat',
        typeMessege:'type a messege..',
        termsConditions:'Terms and Conditions',
        ordinary:'Ordinary',
        ordinaryDesc:'Standerd bus - without meal',
        classic:'Classic',
        classicDesc:'Special bus - with a meal',
        gold:'Gold',
        excellent:'Excellent bus - Flight',
        goldDesc:'with a special meal',
        bill:'bill',
        date:'Date',
        day:'Day',
        travelCost:'Travel Cost',
        bookNumber:'Book Number',
        payment:'Payment',
        choosePaymentMethod:'Choose Payment Method',
        signIn:'Sign in',
        email:'Email',
        country:'Country',
        city:'City',
        address:'Address',
        password:'Password',
        next:'Next',
        login:'Login',
        skipLogin:'Skip Login',
        newMember:'New Member',
        thanks:'Thank You',
        finishBook:'For Finishin your Order',
        willBeContact:'And we will contact you soon',
        forgetPassword:'Forget password',
        home:'Home',
        profile:'Profile',
        books:'Books',
        settings:'Settings',
        exit:'Exit',
        fruits:'Fruits',
        call:'Call',
        share:'Share',
        favourit:'Favourit',
        orders:'orders',
        description:'description',
        category:'category',
        addImage:'Add Image',
        delete:'delete',
        myAds:'My Ads',
        addNewAds:'New Ads'


    },
    ar: {
        travelDate:'تاريخ الذهاب',
        arrivalDate:'تاريخ العودة',
        travelDetails:'تفاصيل الرحلة',
        agree:'موافق',
        goingComingBack:'ذهاب وعودة',
        going:'ذهاب',
        goingFrom:'قيام من',
        backTo:'وصول الي',
        numberOfPersons:'عدد الافراد',
        specialDicount:'خصم خاص',
        Promocode:'بروموكود',
        myBooks:'حجوزاتي',
        currentBooks:'حجوزاتي الحالية',
        previousBooks:'حجوزاتي السابقة',
        travelType:'نوع الرحلة',
        sourceDestination:'القيام والوصول',
        travelNumber:'رقم الرحلة',
        callUs:'اتصل بنا',
        userName:'اسم المستخدم',
        phoneNumber:'رقم الهاتف',
        messege:'رسالة',
        send:'ارسال',
        chat:'المحادثه',
        typeMessege:'ادخل الرسالة',
        termsConditions:'الشروط والحقوق',
        ordinary:'عادية',
        ordinaryDesc:'باص عادي - بدون وجبه',
        classic:'كلاسيك',
        classicDesc:'باص مميز - مع وجبه',
        gold:'ذهبي',
        excellent:'باص فاخر - طيران',
        goldDesc:'مع وجبه مميزه',
        bill:'فاتورة',
        date:'تاريخ',
        day:'اليوم',
        travelCost:'تكلفة الرحلة',
        bookNumber:'رقم الحجز',
        payment:'الدفع',
        choosePaymentMethod:'اختر وسيله للدفع',
        signIn:'تسجيل الدخول',
        email:'البريد الالكتورني',
        country:'الدولة',
        city:'المدينة',
        address:'العنوان',
        password:'كلمة المرور',
        next:'التالي',
        login:'دخول',
        skipLogin:'تخطي التسجيل',
        newMember:'عضو جديد',
        thanks:'نشكركم',
        finishBook:'علي إتمام الحجز',
        willBeContact:'وسيتم التواصل معكم',
        forgetPassword:'نسيت كلمة المرور',
        home:'الرئيسية',
        profile:'الشخصية',
        books:'الحجوزات',
        settings:'الأعدادت',
        exit:'خروج',
        fruits:'فواكه',
        call:'اتصال',
        share:'مشاركة',
        favourit:'مفضلة',
        orders:'الطلبات',
        description:'الوصف',
        category:'الفئة',
        addImage:'اضف صوره',
        delete:'مسح',
        myAds:'اعلاناتي',
        addNewAds:'أضف اعلان'


    }
})
